# Generated by Django 3.0.5 on 2020-04-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200410_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_image',
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='core.Ad'),
            preserve_default=False,
        ),
    ]
