# Generated by Django 3.0.5 on 2020-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200410_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
