# Generated by Django 3.0.5 on 2020-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
